---
repos:
    - repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
          - id: black
            language_version: python3.9
    - repo: https://github.com/Riverside-Healthcare/djLint
      rev: v1.19.1
      hooks:
          - id: djlint-django
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.27.1
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict, -c=.yamllint]
