# Generated by Django 4.0.3 on 2022-05-10 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BiosamplesPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("iri", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "accession",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "accession",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                (
                    "system",
                    models.CharField(
                        choices=[("chicken", "chicken"), ("salmon", "salmon")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="holofood.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SampleMetadataMarker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("iri", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SampleStructuredDatum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measurement", models.CharField(max_length=100)),
                ("units", models.CharField(max_length=100, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("ena", "ena"), ("biosamples", "biosamples")],
                        max_length=15,
                    ),
                ),
                (
                    "marker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="holofood.samplemetadatamarker",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="holofood.biosamplespartner",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="holofood.sample",
                    ),
                ),
            ],
        ),
    ]
