# Generated by Django 4.0.3 on 2022-05-20 17:03

from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BiosamplesPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("iri", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "accession",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "accession",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                (
                    "system",
                    models.CharField(
                        choices=[("chicken", "chicken"), ("salmon", "salmon")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ("accession",),
            },
        ),
        migrations.CreateModel(
            name="SampleAnnotation",
            fields=[
                ("created", models.DateTimeField(auto_created=True)),
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                (
                    "content",
                    martor.models.MartorField(
                        help_text="Markdown document describing an analysis of one or more projects/samples"
                    ),
                ),
                ("author", models.CharField(max_length=200)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SampleMetadataMarker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("iri", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SampleStructuredDatum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measurement", models.CharField(max_length=100)),
                ("units", models.CharField(max_length=100, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("ena", "ena"), ("biosamples", "biosamples")],
                        max_length=15,
                    ),
                ),
                (
                    "marker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="holofood.samplemetadatamarker",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="holofood.biosamplespartner",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structured_metadata",
                        to="holofood.sample",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="samplemetadatamarker",
            index=models.Index(fields=["name"], name="holofood_sa_name_b0e467_idx"),
        ),
        migrations.AddField(
            model_name="sampleannotation",
            name="projects",
            field=models.ManyToManyField(
                related_name="annotations", to="holofood.project"
            ),
        ),
        migrations.AddField(
            model_name="sampleannotation",
            name="samples",
            field=models.ManyToManyField(
                related_name="annotations", to="holofood.sample"
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="holofood.project"
            ),
        ),
    ]
