# Generated by Django 4.0.3 on 2022-05-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holofood", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sampleannotation",
            name="projects",
            field=models.ManyToManyField(
                null=True, related_name="annotations", to="holofood.project"
            ),
        ),
        migrations.AlterField(
            model_name="sampleannotation",
            name="samples",
            field=models.ManyToManyField(
                null=True, related_name="annotations", to="holofood.sample"
            ),
        ),
        migrations.AlterField(
            model_name="sampleannotation",
            name="slug",
            field=models.SlugField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
