# Generated by Django 4.0.3 on 2022-05-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holofood", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="samplemetadatamarker",
            index=models.Index(fields=["name"], name="holofood_sa_name_b0e467_idx"),
        ),
    ]
