# Generated by Django 4.0.3 on 2022-05-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holofood", "0002_alter_sampleannotation_projects_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sampleannotation",
            name="projects",
            field=models.ManyToManyField(
                blank=True, related_name="annotations", to="holofood.project"
            ),
        ),
        migrations.AlterField(
            model_name="sampleannotation",
            name="samples",
            field=models.ManyToManyField(
                blank=True, related_name="annotations", to="holofood.sample"
            ),
        ),
    ]
