# Generated by Django 4.0.3 on 2022-05-16 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("holofood", "0002_samplemetadatamarker_holofood_sa_name_b0e467_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sample",
            options={"ordering": ("accession",)},
        ),
        migrations.AlterField(
            model_name="samplestructureddatum",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="structured_metadata",
                to="holofood.sample",
            ),
        ),
    ]
