# Generated by Django 4.0.3 on 2022-05-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holofood", "0003_alter_sampleannotation_projects_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sampleannotation",
            name="created",
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
