# Generated by Django 4.0.3 on 2022-05-24 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holofood", "0004_alter_sampleannotation_created"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sampleannotation",
            options={
                "permissions": [("publish_annotation", "Can publish an annotation")]
            },
        ),
    ]
