# Generated by Django 4.0.3 on 2022-05-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holofood", "0005_alter_sampleannotation_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sampleannotation",
            name="slug",
            field=models.SlugField(
                max_length=200, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
