# Generated by Django 4.0.3 on 2022-05-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holofood", "0006_alter_sampleannotation_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="samplemetadatamarker",
            name="type",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
