# Generated by Django 4.0.3 on 2022-07-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holofood", "0007_samplemetadatamarker_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="samplemetadatamarker",
            options={"ordering": ("type",)},
        ),
        migrations.AlterModelOptions(
            name="samplestructureddatum",
            options={"ordering": ("marker__type", "marker__name", "id")},
        ),
        migrations.AddField(
            model_name="sample",
            name="has_metagenomics",
            field=models.BooleanField(default=False),
        ),
    ]
