# Generated by Django 4.0.6 on 2022-07-08 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("holofood", "0008_alter_samplemetadatamarker_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenomeCatalogue",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100)),
                ("biome", models.CharField(max_length=200)),
                ("related_mag_catalogue_id", models.CharField(max_length=100)),
                (
                    "system",
                    models.CharField(
                        choices=[("chicken", "chicken"), ("salmon", "salmon")],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Genome",
            fields=[
                (
                    "accession",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("cluster_representative", models.CharField(max_length=15)),
                ("taxonomy", models.CharField(max_length=200)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "catalogue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genomes",
                        to="holofood.genomecatalogue",
                    ),
                ),
            ],
        ),
    ]
