# Generated by Django 4.0.6 on 2022-07-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holofood", "0009_genomecatalogue_genome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genome",
            name="metadata",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
