# Generated by Django 4.0.6 on 2022-07-14 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("holofood", "0010_alter_genome_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="ViralCatalogue",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100)),
                ("biome", models.CharField(max_length=200)),
                (
                    "system",
                    models.CharField(
                        choices=[("chicken", "chicken"), ("salmon", "salmon")],
                        max_length=10,
                    ),
                ),
                (
                    "related_genome_catalogue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="viral_catalogues",
                        to="holofood.genomecatalogue",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="genome",
            options={"ordering": ("accession",)},
        ),
        migrations.AlterField(
            model_name="genome",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="ViralFragment",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("contig_id", models.CharField(max_length=100)),
                ("mgnify_analysis_accession", models.CharField(max_length=12)),
                ("start_within_contig", models.IntegerField()),
                ("end_within_contig", models.IntegerField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "viral_type",
                    models.CharField(
                        choices=[("phage", "phage"), ("prophage", "prophage")],
                        max_length=10,
                    ),
                ),
                (
                    "catalogue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viral_fragments",
                        to="holofood.viralcatalogue",
                    ),
                ),
                (
                    "cluster_representative",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cluster_members",
                        to="holofood.viralfragment",
                    ),
                ),
                (
                    "host_mag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="viral_fragments",
                        to="holofood.genome",
                    ),
                ),
            ],
        ),
    ]
