# Generated by Django 4.0.6 on 2022-08-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holofood", "0013_auto_20220805_1049"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="samplestructureddatum",
            name="partner",
        ),
        migrations.AddField(
            model_name="samplestructureddatum",
            name="partner_iri",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="samplestructureddatum",
            name="partner_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="BiosamplesPartner",
        ),
    ]
