# Generated by Django 4.0.6 on 2022-08-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holofood", "0016_sample_has_metabolomics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplemetadatamarker",
            name="iri",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="samplemetadatamarker",
            name="type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="samplestructureddatum",
            name="partner_iri",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="samplestructureddatum",
            name="partner_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="samplestructureddatum",
            name="units",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
