# Generated by Django 4.0.6 on 2022-08-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holofood", "0017_alter_samplemetadatamarker_iri_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="ena_run_accessions",
            field=models.JSONField(default=list),
        ),
    ]
