# Generated by Django 4.1 on 2022-09-06 15:36
import logging

from django.db import migrations, models


def set_animal_code_from_metadata(apps, schema_editor):
    """
    Sets the Animal Code for Samples where this was not set during creation.
    """
    Sample = apps.get_model("holofood", "Sample")
    for sample in Sample.objects.filter(animal_code=""):
        animal_code = sample.structured_metadata.filter(
            marker__name="host subject id"
        ).first()
        if animal_code:
            sample.animal_code = animal_code.measurement
            logging.info(f"Setting animal_code={animal_code.measurement} on {sample}")
            sample.save()


class Migration(migrations.Migration):

    dependencies = [
        ("holofood", "0020_sample_metabolights_files_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="animal_code",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.RunPython(set_animal_code_from_metadata, migrations.RunPython.noop),
    ]
