# Generated by Django 4.1 on 2022-10-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holofood", "0021_sample_animal_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="viralfragment",
            name="taxonomy",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
