# Generated by Django 4.1.2 on 2023-02-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holofood", "0022_viralfragment_taxonomy"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SampleAnnotation",
            new_name="AnalysisSummary",
        ),
        migrations.AlterModelOptions(
            name="analysissummary",
            options={
                "permissions": [
                    ("publish_annotation", "Can publish an analysis summary")
                ]
            },
        ),
        migrations.AddField(
            model_name="analysissummary",
            name="genome_catalogues",
            field=models.ManyToManyField(
                blank=True,
                related_name="analysis_summaries",
                to="holofood.genomecatalogue",
            ),
        ),
        migrations.AddField(
            model_name="analysissummary",
            name="viral_catalogues",
            field=models.ManyToManyField(
                blank=True,
                related_name="analysis_summaries",
                to="holofood.viralcatalogue",
            ),
        ),
        migrations.AlterField(
            model_name="analysissummary",
            name="projects",
            field=models.ManyToManyField(
                blank=True, related_name="analysis_summaries", to="holofood.project"
            ),
        ),
        migrations.AlterField(
            model_name="analysissummary",
            name="samples",
            field=models.ManyToManyField(
                blank=True, related_name="analysis_summaries", to="holofood.sample"
            ),
        ),
    ]
