# Generated by Django 4.1.2 on 2023-02-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holofood", "0023_rename_sampleannotation_analysissummary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analysissummary",
            options={
                "permissions": [
                    ("publish_annotation", "Can publish an analysis summary")
                ],
                "verbose_name_plural": "analysis summaries",
            },
        ),
        migrations.AlterField(
            model_name="genomecatalogue",
            name="id",
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="viralcatalogue",
            name="id",
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
