# Generated by Django 4.1.2 on 2023-02-13 17:24

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ("holofood", "0026_alter_sample_animal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysissummary",
            name="projects",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="project",
        ),
        migrations.AlterField(
            model_name="analysissummary",
            name="content",
            field=martor.models.MartorField(
                help_text="Markdown document describing an analysis of one or more catalogues/samples"
            ),
        ),
        migrations.DeleteModel(
            name="Project",
        ),
    ]
