# Generated by Django 4.1.2 on 2023-02-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holofood", "0027_remove_analysissummary_projects_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sample",
            name="has_metabolomics",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="has_metagenomics",
        ),
        migrations.AddField(
            model_name="sample",
            name="sample_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("metagenomic", "metagenomic"),
                    ("metabolomic", "metabolomic"),
                    ("histological", "histological"),
                    ("host_genomic", "host_genomic"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
