# Generated by Django 4.2 on 2023-04-25 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holofood", "0030_remove_sample_metabolights_files_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="animal_code",
        ),
    ]
