# Generated by Django 4.2 on 2023-04-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holofood", "0031_remove_animal_animal_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="sample_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("metagenomic_assembly", "metagenomic_assembly"),
                    ("metagenomic_amplicon", "metagenomic_amplicon"),
                    ("metabolomic", "metabolomic"),
                    ("metabolomic_targeted", "metabolomic_targeted"),
                    ("histological", "histological"),
                    ("host_genomic", "host_genomic"),
                    ("transcriptomic", "transcriptomic"),
                    ("metatranscriptomic", "metatranscriptomic"),
                    ("iodine", "iodine"),
                    ("fatty_acids", "fatty_acids"),
                    ("heavy_metals", "heavy_metals"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
