# Generated by Django 4.2 on 2023-04-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holofood", "0032_alter_sample_sample_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sample",
            name="ena_run_accessions",
        ),
        migrations.AlterField(
            model_name="sample",
            name="sample_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("metagenomic_assembly", "metagenomic_assembly"),
                    ("metagenomic_amplicon", "metagenomic_amplicon"),
                    ("metabolomic", "metabolomic"),
                    ("metabolomic_targeted", "metabolomic_targeted"),
                    ("histological", "histological"),
                    ("host_genomic", "host_genomic"),
                    ("transcriptomic", "transcriptomic"),
                    ("metatranscriptomic", "metatranscriptomic"),
                    ("iodine", "iodine"),
                    ("fatty_acids", "fatty_acids"),
                    ("heavy_metals", "heavy_metals"),
                    ("inflammatory_markers", "inflammatory_markers"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
