# Generated by Django 4.2 on 2024-01-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holofood", "0034_alter_animal_options_alter_viralfragment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viralfragment",
            name="viral_type",
            field=models.CharField(
                choices=[
                    ("viral_sequence", "viral_sequence"),
                    ("prophage", "prophage"),
                ],
                max_length=15,
            ),
        ),
    ]
