# Generated by Django 4.2 on 2024-03-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holofood", "0035_alter_viralfragment_viral_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animalstructureddatum",
            name="measurement",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="samplestructureddatum",
            name="measurement",
            field=models.CharField(max_length=300),
        ),
    ]
