# Generated by Django 4.2 on 2024-06-20 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("holofood", "0036_alter_animalstructureddatum_measurement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenomeSampleContainment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("containment", models.FloatField(default=0)),
                (
                    "genome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples_containing",
                        to="holofood.genome",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genomes_contained",
                        to="holofood.sample",
                    ),
                ),
            ],
            options={
                "ordering": ("genome", "-containment"),
            },
        ),
    ]
