apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: holofood-volume-claim
  namespace: holofood-hl-prod
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  volumeName: holofood-vol-1
