apiVersion: v1
kind: PersistentVolume
metadata:
  name: holofood-vol-1
  namespace: holofood-hl-prod
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - nfsvers=3
  nfs:
    server: hh-isi-srv-vlan1496.ebi.ac.uk
    path: /ifs/public/rw/metagenomics/holofood_data_portal
