project:
    type: website

execute:
    freeze: auto

website:
    title: HoloFood Data Portal Documentation
    page-footer: This project has received funding from the European Union’s
        Horizon 2020 research and innovation programme under grant agreement
        No 817729
    favicon: img/hf-logo-brand.png
    page-navigation: true

    repo-url: https://github.com/ebi-metagenomics/holofood-database
    repo-subdir: docs
    repo-actions: [edit, issue]

    navbar:
        right:
            - href: http://holofooddataportaldev-env.eba-jwzhg3z2.eu-west-1.elasticbeanstalk.com
              text: Data Portal

    sidebar:
        style: docked
        search: true

        contents:
            - href: index.qmd
              text: Docs home
              icon: box
            - href: datasets.qmd
            - href: website.qmd
            - href: api.ipynb
            - text: '---'
            - href: tutorial.ipynb
            - text: '---'
            - href: publications.qmd
            - text: '---'
            - href: partners.qmd

        tools:
            - icon: github
              menu:
                  - text: Data Portal Repository
                    url: https://github.com/ebi-metagenomics/holofood-database
                  - text: Documentation source
                    url: https://github.com/ebi-metagenomics/holofood-database/docs
            - icon: question-circle-fill
              text: Help
              href: mailto:holofood-help@ebi.ac.uk
format:
    html:
        theme:
            - zephyr
            - styles.scss
        toc: true
