name: Testing

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'requirements*.txt'
      - uses: nanasess/setup-chromedriver@master
      - name: Configure resolution
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
      - name: Install dependencies
        run: |
          python -m pip install -r requirements-dev.txt
      - name: Make stylesheet
        run: |
          python manage.py compilescss
      - name: Run Pytest
        run: |
          pytest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./test-results/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: website-test-screenshots
          path: screenshot_website*.png
